# tim-go Global Configuration

# casbin configuration
#casbin:
#    model-path: './resource/rbac_model.conf'
#
## jwt configuration
#jwt:
#    signing-key: 'tim-go'

# mysql connect configuration
mysql:
    username: root
    password: 'root'
    path: 'localhost:3306'
    db-name: 'timgo'
    config: 'charset=utf8&parseTime=True&loc=Local'
    max-idle-conns: 300
    max-open-conns: 2000
    log-mode: false

# system configuration
system:
    use-multipoint: false
    env: 'public'  # Change to "develop" to skip authentication for development mode /public
    addr: 9991
    log-mode: true
    db-type: "mysql"  # support mysql/sqlite

# captcha configuration
captcha:
    key-long: 6
    img-width: 240
    img-height: 80

# logger configuration
log:
    prefix: '[tim-go]'
    log-file: true
    stdout: 'DEBUG'
    file: 'DEBUG'